feat(zero): add icon for zero / gamedao
paritytech/substrate-telemetry pull request #290
Opened 2020-09-26 18:16 UTC by 2075

hey there,

we are building zero / gamedao and thought it would be great to add our icon, too :)
hope that works as intended.

greetings
marco

2020-09-30 13:22 UTC, maciejhirsz requested changes

2020-09-30 13:22 UTC, maciejhirsz commented on frontend/src/icons/zero.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 342 342"><defs><style>.a{fill:none;}.b{fill:#231f20;}</style></defs><title>z-ctrl-blk</title><rect class="a" width="342" height="342"/><path class
Swapping the fill color to `currentColor` so it works nice with the styles.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 342 342"><defs><style>.a{fill:none;}.b{fill:currentColor;}</style></defs><title>z-ctrl-blk</title><rect class="a" width="342" height="342"/><path class="b" d="M152.35,170.46l-12.18-12.19a.5.5,0,0,0-.35-.14.48.48,0,0,0-.34.14l-34.41,34.41V106.15a.51.51,0,0,0-.3-.46l-.19,0a.52.52,0,0,0-.35.14L39.58,170.46a.49.49,0,0,0-.15.34.51.51,0,0,0,.15.35l12.18,12.18a.47.47,0,0,0,.35.14.45.45,0,0,0,.34-.14l34.41-34.41v86.54a.49.49,0,0,0,.3.45.43.43,0,0,0,.19,0,.45.45,0,0,0,.34-.15l64.66-64.65A.49.49,0,0,0,152.35,170.46Z"/><path class="b" d="M185.24,49.85,173.06,37.66a.49.49,0,0,0-.34-.14.52.52,0,0,0-.35.14l-56,56a.49.49,0,0,0,0,.69l12.18,12.19a.52.52,0,0,0,.35.14.49.49,0,0,0,.34-.14l56-56A.47.47,0,0,0,185.24,49.85Z"/><path class="b" d="M229.1,93.7,216.92,81.52a.51.51,0,0,0-.34-.14.52.52,0,0,0-.35.14l-56,56a.49.49,0,0,0,0,.69l12.18,12.19a.52.52,0,0,0,.35.14.49.49,0,0,0,.34-.14l56-56A.49.49,0,0,0,229.1,93.7Z"/><path class="b" d="M207.17,71.77,195,59.59a.49.49,0,0,0-.34-.14.52.52,0,0,0-.35.14l-56,56a.49.49,0,0,0,0,.69l12.18,12.19a.52.52,0,0,0,.35.14.49.49,0,0,0,.34-.14l56-56A.49.49,0,0,0,207.17,71.77Z"/><path class="b" d="M219.71,243.93H176.34V188.38a.49.49,0,0,0-.3-.45.43.43,0,0,0-.19,0,.49.49,0,0,0-.35.15l-64.65,64.65a.49.49,0,0,0,0,.69L123,265.57a.5.5,0,0,0,.35.14.48.48,0,0,0,.34-.14l34.41-34.41v74.35a.49.49,0,0,0,.49.49h17.23a.49.49,0,0,0,.49-.49V262.14h43.37a.49.49,0,0,0,.49-.49V244.42A.49.49,0,0,0,219.71,243.93Z"/><path class="b" d="M305.86,170.46l-56-56.05a.51.51,0,0,0-.7,0l-56,56.05a.48.48,0,0,0-.14.34.5.5,0,0,0,.14.35l56,56a.51.51,0,0,0,.7,0l56-56A.49.49,0,0,0,305.86,170.46Zm-56.39,31.33-31-31,31-31,31,31Z"/></svg>
```

2020-09-30 13:27 UTC, 2075 commented
thanks!

2020-09-30 13:27 UTC, maciejhirsz approved these changes

2020-09-30 15:17 UTC, merged

2020-10-02 10:58 UTC, maciejhirsz commented
Should be live now.